---
title: "02402 - Statistics Projekt 2: Bmi undersøgelse"
output: 
  html_notebook:
    toc: true
    theme: united
    code_folding: hide
author: "Daniel F. Hauge - s2011687"
---

```{r}
D <- read.table("E:\\repo\\02402-statistics-exercises\\Project2/bmi2_data.csv", header=TRUE, sep=";", as.is=TRUE)
D$logbmi <- log(D$bmi)
n <- nrow(D)
```

Dette projekt består af en statistisk analyse af et datasæt med mennesker. Projektet forsøger at kaste lys på BMI med statistik. 
Projektet henvender sig til læserer som er familiær med projekt beskrivelsen fra statistik kurset 02402 fra DTU og befærder sig komfortabelt i statistiske begreber og metoder.

Projektet er lavet som en R notebook, og indeholder derfor områder hvor R er brugt som redskab til udregning og plot optegninger. Bokse med skriften ```Code``` indikere at der er blevet kodet noget i R til at udregne, tegne eller gemme værdier til senere brug. R koden kan findes på følgende måder:


- Se den medfølgende ".R" fil, eller via på: https://github.com/DanielHauge/02402-statistics/blob/master/Project1/projekt_code_only.R 
- Se den medfølgende ".rmd" fil, eller på: https://github.com/DanielHauge/02402-statistics/blob/master/Project1/project.rmd
- Projektet kan også findes i renderet form med kode afsnit på: https://htmlpreview.github.io/?https://github.com/DanielHauge/02402-statistics/blob/master/Project1/project.nb.html



\pagebreak

# a) Descriptiv analyse

# b) Multipel lineær regressionsmodel

# c) Model parametre

# d) Model kontrol

# e) Alders koefficient konfidensinterval

# f) Hypotesetest

# g) Backward selection

# h) Prædiktioner